name: CI/CD Pipeline for Repo2

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Download Repo1 Artifact
        uses: actions/download-artifact@v3
        with:
          name: repo1-artifact

      - name: Move Repo1 Artifact to Local Maven Repo
        run: |
          mkdir -p ~/.m2/repository/com/example/repo1/1.0-SNAPSHOT
          mv repo1-1.0-SNAPSHOT.jar ~/.m2/repository/com/example/repo1/1.0-SNAPSHOT/repo1-1.0-SNAPSHOT.jar
      
      - name: Build and Package
        run: mvn clean package

      - name: Upload Repo1 Artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo1-artifact
          path: target/repo1-1.0-SNAPSHOT.jar